### ISSUE TITLE
Should exceptions raised by underlying libraries be wrapped or passed through?

### ISSUE THREAD

**Issue by felixc** [plaid/plaid-python#109]
Currently, if an library used within the Plaid client throws an exception, it won't always be caught, wrapped, and re-thrown as a `PlaidError` or subclass. For example, `requests` may throw a `ConnectionError` when there's a network problem.

This isn't necessarily an issue, but may rather just be a design choice in the library.

On the one hand, it makes it a bit difficult for users, who won't necessarily know what libraries are used internally, or what exceptions they may thrown. On the other hand, you don't control what exceptions the libraries you use throw, and you can't necessarily anticipate and catch them all, so users may have to be prepared for the eventuality that one leaks out anyway, and in that case, the supposed benefit from catching and wrapping them all is reduced.

Do you have a policy/preference/philosophy either way? If we see an exception thrown by an inner library, should we consider that a bug and report it as an issue?

In particular, we've seen the `ConnectionError` from `requests` case actually come up in a context where we only expected `PlaidError` (and subclasses). It originally came from https://github.com/plaid/plaid-python/blob/494244bd9820bfd80177878149591ca53f135932/plaid/requester.py#L14-L28

Would you consider that in this case this library should check for that and re-raise it as a `PlaidError`?

Thanks!

**Comment by felixc** [comment]
This is somewhat related to #106

**Comment by michaelckelly** [comment]
@felixc - https://github.com/plaid/plaid-python/pull/108 should address part of #106 and we hope to merge and publish that fix today.

**Comment by felixc** [comment]
Great; #106 did indeed handle the JSON response case, but what are your thoughts on the broader question of whether all underlying library exceptions should be wrapped? For example, `ConnectionError` from `requests`? Is it a bug that that isn't caught and rethrown?

**Comment by joyzheng** [comment]
> but what are your thoughts on the broader question of whether all underlying library exceptions should be wrapped?

I'd lean towards not wrapping library errors like `ConnectionError` into `PLAID_ERROR` by default, because the expected programmatic handling is a bit different. More specifically, right now `PLAID_ERROR` always indicates that something went wrong on Plaid's end, and that the best way to address it is to retry the request. On the other handle, `ConnectionError` could indicate an issue on our end, or it could point to some configuration/firewall configuration issue. 

I wonder if we could include an option to pass in a custom requestor and/or error handler to the client initialization. That would make it easier to add error wrapping to all Plaid requests without having to adjust each call site. Would that help in your case?

**Comment by felixc** [comment]
That makes sense; perhaps a subclass of `PlaidError` is not ideal — but it could still be wrapped in a library-specific exception (for example `plaid.OperationalError` or something?) or just have it documented that `requests.RequestException` and subclasses may be thrown?

As another supporting example, we just got a bunch of `requests.ReadTimeout` exceptions that were not caught, because the current interface neither wraps them into something we expect to catch *nor* does it document that they may be thrown.

I for one am OK with either approach, but the end state that we'd like to get to is that we can catch and understand essentially all of the exceptions that may be thrown by using this library, and either retry or rethrow them as appropriate. That could be done by either wrapping them into a common type, or documenting all the ones that the user needs to watch out for (the downside of this is that it makes your internal library use part of your public API, since callers will expect to catch `requests` exceptions).

The custom error handler approach is interesting... Do you have an example of how that might look, e.g. is that pattern used in any common libraries that could be used for comparison/reference?

**Comment by joyzheng** [comment]
> because the current interface neither wraps them into something we expect to catch nor does it document that they may be thrown.

Gotcha -- definitely agree that we should make it easier to handle other errors + make it more obvious that they can be thrown. 

Going to do some more research on other libraries + get back to you on this -- thanks for your patience here

**Comment by joyzheng** [comment]
Thanks again for your patience, the latest update here is that we're leaning towards is creating a new `CONNECTION_ERROR` value of `error_type` (along with some new `error_code` values). The benefit is that this keeps the errors clearly distinguishable from the `PLAID_ERROR` value of `error_type`, but lets us morph known request error cases into the same `PlaidError` python class for easier code handling.

The next step is to pin down the error codes (to keep it consistent about it across client libraries for different languages) and figure out whether we want to roll this into a major version bump vs. a minor bump (concern here would be around breaking any existing error handling which assumes the `request` library errors, tbd whether I'm just being overly cautious with respect to that though).

**Comment by felixc** [comment]
Just noting this change because it's somewhat related to this issue. Looks like in the latest release of the client, `requester` was moved into the `internal` directory, presumably implying callers should not be importing it. This means we can no longer do `from plaid.requester import requests`, and instead need to depend on and import `requests` directly.

This is pretty low-risk, but in theory means there could be an API mismatch and runtime errors if the version we're depending on isn't the same one that your code was written against and had a breaking change.

Wrapping the implementation detail and related exceptions, and making it so callers can't tell that you're using `requests`, and thus don't need to import it to catch errors, would alleviate that risk.

**Comment by cgfarmer4** [comment]
Closing due to age. Please let me know if this is still an issue.

**Comment by felixc** [comment]
> Please let me know if this is still an issue.

Unless I'm missing something, I believe it still is? The example code looks the same, and I don't see anything catching/wrapping the underlying `requests` exceptions.

**Comment by cgfarmer4** [comment]
@felixc we've made updates to our `beta` repository that should allow more flexibility here. Let me know if that helps.
