### ISSUE TITLE
client ID is only authorized to use Plaid Link

### ISSUE THREAD

**Issue by holtc** [plaid/plaid-python#131]
I'm trying to create an Item through the python library, not using link, which seems to be supported according to the present code.  However, the response contains the following error:

plaid.errors.InvalidInputError: your client ID is only authorized to use Plaid Link. head to the docs (https://plaid.com/docs) to get started.

Is there any way to create an Item without using Link?  Might be related to [this](https://github.com/plaid/plaid-ruby/issues/168)?

**Comment by r-ohan** [comment]
@holtc Hello! item/create calls can be used in sandbox to help with writing integration tests, but Plaid Link is the only way to create items in the Production environment.

Please direct any further questions to: https://dashboard.plaid.com/support

Thanks!
