### ISSUE TITLE
Hi, I want to see lists of all categories/category id's

### ISSUE THREAD

**Issue by TheoSeo93** [plaid/plaid-python#132]
I can't see the list of it anywhere from the website. Where can I see that?

**Comment by ravron** [comment]
Hi @TheoSeo93, you may see a list of all transaction categories by POSTing to the `/categories/get` endpoint. For example:

```
curl -X POST https://sandbox.plaid.com/categories/get \
  -H 'Content-Type: application/json' \
  -d '{}'
```

This endpoint is [listed in our documentation](https://plaid.com/docs/api/#category-overview). I hope that helps!
