### ISSUE TITLE
Support for custom request headers/fields

### ISSUE THREAD

**Issue by kjwong** [plaid/plaid-python#133]
plaid-python doesn't give us the functionality to add custom headers/fields to requests, which we need for routing requests through our secure network layer. As a workaround, we point to our fork of plaid-python that adds that functionality. 

We'd love to see this functionality in plaid-python so we can stop maintaining our fork. Specifically for our use case, this is the ability to add custom request headers and pass values for `proxies` and `verify` to python `requests`. Thanks!

**Comment by michaelckelly** [comment]
@kjwong - Thanks for the feedback and explanation -- let me follow up on this shortly!

**Comment by michaelckelly** [comment]
@kjwong would you be willing to share your fork? I'm not seeing it anywhere publicly

**Comment by kjwong** [comment]
@michaelckelly shared with you

**Comment by michaelckelly** [comment]
Awesome - got it @kjwong, we'll work to incorporate the functionality in your fork into the library. Will keep this issue up-to-date.

**Comment by kjwong** [comment]
Great to hear -- thanks!

**Comment by kjwong** [comment]
@michaelckelly any updates on this?

**Comment by pbernasconi** [comment]
@kjwong – could you provide a code sample of how you would like to add your own headers to the python client library? Alternatively, could I suggest you open a PR with the code that you've written in your fork? That would definitely expedite this feature request!

I'm all for this feature - but could use a starting point to kick this off

**Comment by kjwong** [comment]
@pbernasconi I opened a PR with the changes we've made to allow our proxy to work: https://github.com/plaid/plaid-python/pull/172. The variables have "petal" in them but the logic should be generalizable. Thanks for taking a look!

**Comment by cgfarmer4** [comment]
Passing custom headers is available in our new beta versions. Please let me know if this is still an issue.
