### ISSUE TITLE
Tests for python 3.7

### ISSUE THREAD

**Issue by samuelcolvin** [plaid/plaid-python#140]
Python 3.7 has been released for months.

Surely we should have tests run for 3.7?

**Comment by stephenjayakar** [comment]
Hey @samuelcolvin, we are planning on pinning our library to Python 3.7 in the next major release, which means that we will also be testing on 3.7.  See this thread.
https://github.com/plaid/plaid-python/issues/175

**Comment by samuelcolvin** [comment]
3.9 if now released... 

But great work on being July 2018.
