### ISSUE TITLE
Change log is missing

### ISSUE THREAD

**Issue by Perlence** [plaid/plaid-python#141]
I couldn't find the detailed log of library changes, is there one? I find upgrading the library without referring to a change log unsettling, it's not clear what can go wrong.

**Comment by r-ohan** [comment]
Hi @Perlence, check out the change log here: https://github.com/plaid/plaid-python/releases. We use semantic versioning, so minor version increases are backwards-compatible.

**Comment by Perlence** [comment]
Thank you, it was there the whole time!
