### ISSUE TITLE
AttributeError: module 'plaid' has no attribute 'Client'

### ISSUE THREAD

**Issue by DShep68** [plaid/plaid-python#143]
I'm trying to run the server.py file on my mac but I continue to have this error that says no attribute client and I'm not sure where to go from here. Please let me know some ways to fix this issue

**Comment by DShep68** [comment]
`client = plaid.Client(client_id = PLAID_CLIENT_ID, secret=PLAID_SECRET,
AttributeError: module 'plaid' has no attribute 'Client'`

**Comment by SterlingButters** [comment]
What version of Plaid are you using? What does your import statements look like?

**Comment by shaunharker** [comment]
I ran into this because I installed plaid via `pip install plaid` which isn't the right module. Instead, `pip install plaid-python` worked.

**Comment by gsalem** [comment]
I am running into the same issue even after installing `plaid-python` which tells me that the requirements are satisfied. I get this error:

`Traceback (most recent call last):
  File "server.py", line 28, in <module>
    client = plaid.Client(client_id=PLAID_CLIENT_ID, secret=PLAID_SECRET,
AttributeError: module 'plaid' has no attribute 'Client'`

Did anyone find a solution to this?

**Comment by ravron** [comment]
Thanks @shaunharker for the suggestion! @DShep68, did `pip install plaid-python` solve your issue?

**Comment by fexlneb** [comment]
Having this same exact issue. Any solution?

**Comment by fexlneb** [comment]
@shaunharker - can you share how you got your server.py to import plaid-python? i cannot import a module name with a dash it appears.

it seems if i import plaid it will import the "plaid" module and not "plaid-python". How can i import "plaid-python" and not "plaid"??

**Comment by skylarmb** [comment]
Hello all, closing this as it does not seem to be an issue with this library, and rather an issue with installing/importing `plaid` instead of `plaid-python`. Additional comments that may help you resolve your issue can be found here: https://github.com/plaid/plaid-python/issues/120
