### ISSUE TITLE
Add Changelog to releases

### ISSUE THREAD

**Issue by tomhamiltonstubber** [plaid/plaid-python#158]
Hi guys,

Can you update the releases with a change log please? Sounds like there might be breaking changes in a 3.0.0 release.

**Comment by samuelcolvin** [comment]
hi @michaelckelly, it looks like you used to add a release to github when you released to pypi, but stopped about 6 months ago. Was that intentional?

There's also no information whatsoever no the pypi release. 

Is this library definitely for external use?

**Comment by diogovk** [comment]
It's extremely important that you document breaking changes.
Was the renaming of delete->remove documented somewhere?
What other breaking changes happened lately that I might be missing?
