### ISSUE TITLE
Python version support

### ISSUE THREAD

**Issue by nurdyguy** [plaid/plaid-python#175]
What python version(s) are currently supported? 
Issue https://github.com/plaid/plaid-python/issues/140 was reported in January 2019 but nobody responded to it. 
In issue https://github.com/plaid/plaid-python/issues/143 (which is the actual problem I'm having) @SterlingButters asked "What version of Plaid are you using?" which might imply that it makes a difference (I'm on 3.7.1).  
I also noticed that in the quickstart project it is using 2.7 and the requirements.txt includes the line "wsgiref==0.1.2 ; python_version < '3.2'" which certainly wouldn't work with my version.

**Comment by omar3903** [comment]
Just faced this problem today, hope to see a reply on here soon.

**Comment by sstylianides** [comment]
I'm using Python 3.7 and it's working for me.

**Comment by har96** [comment]
Python 3.8 on Mac doesn't seem to work:

    Python 3.8.5 (default, Jul 21 2020, 10:48:26)
    [Clang 11.0.3 (clang-1103.0.32.62)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from plaid import Client
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'Client' from 'plaid' (unknown location)

Reinstalled with Python 3.7 and it works just fine.

**Comment by stephenjayakar** [comment]
Hey @nurdyguy, we are planning on pinning our plaid-python CLib release to Python version 3.7 with the next major release.  I hope this helps.

**Comment by stephenjayakar** [comment]
As of now we support the Python versions listed here:
https://github.com/plaid/plaid-python/blob/master/setup.py

but run our tests only for Python 2.7 and Python 3.6.
https://github.com/plaid/plaid-python/blob/master/tox.ini
