### ISSUE TITLE
Python docs not explaining API version parameter

### ISSUE THREAD

**Issue by Skorkmaz88** [plaid/plaid-python#176]
Neither python docs nor the readme file explains or demonstrates how API version parameter works in the client class' constructor. Assumption is , give in the source code it is mentioned as string, it is the date with dashes as in the website as string , is that correct ?

**Comment by pbernasconi** [comment]
@Skorkmaz88 This is good feedback – I'll look into documenting this shortly in either the README here or our official plaid.com/docs!
