### ISSUE TITLE
Liabilities not present in plaid-python==3.3.3

### ISSUE THREAD

**Issue by hackath0r** [plaid/plaid-python#180]
I can see that Liabilities is exposed to the client in the master branch. However, after installing the latest version (3.3) of plaid-python from pip, Liabilities is not present.

**Comment by ipam73** [comment]
+1 to this, I'm looking to use Liabilities with the latest plaid-python from pip

**Comment by pbernasconi** [comment]
@hackath0r @ipam73 – Thanks for flagging this.

I've just released [v3.4.0](https://pypi.org/project/plaid-python/) which includes support for Liabilities. You can check out the [plaid.com/docs#liabilities](https://plaid.com/docs#liabilities) documentation and select "python" as your code-language in the top right to find code-samples to integrate with the new product.

Thanks for your patience!
