### ISSUE TITLE
Incorrect Python Documentation

### ISSUE THREAD

**Issue by JuanPabloRN30** [plaid/plaid-python#186]
On the integration with Dwolla the "Step 4: Write server-side handler"

the snippet example:
`dwolla_response = 
client.Processor.dwollaProcessorTokenCreate(access_token, 
account_id)`

should be:
`dwolla_response = 
client.Processor.dwollaBankAccountTokenCreate(access_token, account_id)`

This can generate confusion. Please update the docs! :)

**Comment by davidzhanghp** [comment]
Hi @JuanPabloRN30 

Appreciate your feedback on this. Since this issue was created we've changed to a generic ProcessorTokenCreate function so it is no longer necessary.

https://plaid.com/docs/dwolla/

Thanks,
David @ Plaid
