### ISSUE TITLE
error while getting processor token of Modern Treasury 

### ISSUE THREAD

**Issue by Saurabh-Sn** [plaid/plaid-python#190]
'Processor' object has no attribute 'modernTreasuryProcessorTokenCreate'Type a message
![image_2019_12_11T05_12_47_227Z](https://user-images.githubusercontent.com/14322809/70597798-47a05b00-1c0f-11ea-882f-4ba02ca1cfb7.jpg)

**Comment by wholien** [comment]
https://github.com/plaid/plaid-python/pull/191 should fix

**Comment by Saurabh-Sn** [comment]
Issue fixed
