### ISSUE TITLE
Retrieve Transactions Example 

### ISSUE THREAD

**Issue by pythonympho** [plaid/plaid-python#193]
The retrieve transactions example is not listing the transactions.  Does anyone have a sure way to print the transactions into the terminal window or export to .csv?

**Comment by stephen-krause** [comment]
Hi @pythonympho, sorry for the late response this issue.

If you are are trying the transactions example listed in the README, you may need to update the `start_date` and `end_date` to be a more recent timeframe (i.e., dates within the current year). We have seen similar reports where requests made with the default dates in the `sandbox` environment will return an empty transactions object, so this may be a possible cause for the omission.

I hope this helps. If this does not solve the issue, please provide more details about your request through the [Plaid Dashboard](https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/product-functionality).  Have a great day!
