### ISSUE TITLE
Plaid is not defined error message. 

### ISSUE THREAD

**Issue by Leke-Ariyo** [plaid/plaid-python#194]
Python 3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> plaid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'plaid' is not defined

I have plaid-python>=3.0.0 in my requirements.txt file and was able to successfully install it. Also I imported it in my server.py line 4.

**Comment by cgfarmer4** [comment]
@Leke-Ariyo hi there- thanks for reporting! Please reopen if this is still an issue for you.
