### ISSUE TITLE
Using a mutable value as default

### ISSUE THREAD

**Issue by frnhr** [plaid/plaid-python#201]
Using mutable default values is almost not what was intended.

Ref:
 * "Important warning" under [4.7.1. Default Argument Values](https://docs.python.org/3/tutorial/controlflow.html#default-argument-values) in the official Python docs tutorial
 * [Mutable Default Arguments ](https://docs.python-guide.org/writing/gotchas/)
 * Warning `B006` in [List of warnings](https://github.com/PyCQA/flake8-bugbear/blob/master/README.rst) in flake8-bugbear

Please update:

``` python
class Institutions(API):
    ...
    def search(self, query, _options={}, products=None):
        ...
```

to something like this:

``` python
class Institutions(API):
    ...
    def search(self, query, _options=None, products=None): 
        _options = options or None
        ...
```

**Comment by davidzhanghp** [comment]
Hi @frnhr , I appreciate you taking the time to create this issue. I've addressed this in https://github.com/plaid/plaid-python/pull/217
