### ISSUE TITLE
API version pinning documented incorrectly

### ISSUE THREAD

**Issue by hkhanna** [plaid/plaid-python#202]
The versioning section in the README uses the wrong kwarg to set the Client to a specific version. 

The README says the kwarg is `version`:
```
client = Client(
  ...
  version='2019-05-29'  # Specify API version
)
```
A review of the source indicates that it should actually be `api_version`:
```
client = Client(
  ...
  api_version='2019-05-29'  # Specify API version
)
```

**Comment by daniellacoste** [comment]
Hey there @hkhanna - thanks for flagging this. LGTM! 🥌
