### ISSUE TITLE
http_request in plaid/requester.py fails with Attribute Error

### ISSUE THREAD

**Issue by WilliamParks** [plaid/plaid-python#216]
The method http_request in plaid.requester is a wrapper around _requests_http_request, in the same file. 

http_request sends a "method" value of none to _requests_http_request, which then calls lower() from it.

```
def _requests_http_request(
        url,
        method,
        data,
        headers,
        timeout=DEFAULT_TIMEOUT):
    normalized_method = method.lower()
     # Rest of function removed here for brevity

def http_request(
        url,
        method=None,
        data=None,
        headers=None,
        timeout=DEFAULT_TIMEOUT,
        is_json=True):
    response = _requests_http_request(
        url,
        method,
        data or {},
        headers or {},
        timeout)
```

**Comment by skylarmb** [comment]
hi there @WilliamParks what did you do that caused this error? Were you calling one of the plaid library methods like `client.Auth.get` etc or were you trying to use `http_request` directly in your code? `http_request` is internal (or at least should be lol, maybe ill make a PR for that) to this library and you should not be using in your code

**Comment by WilliamParks** [comment]
Hi @skylarmb! To be honest, I can't remember what I was working on. I was mainly playing around with things, not for an actual project. It's likely I called something that's supposed to be internal.

Still, it seemed odd to me that using the default parameter assignment for method in http_request will always cause an AttributeError, in the current design.

**Comment by skylarmb** [comment]
hey @WilliamParks thanks for the clarification. that method is only used to define [this](https://github.com/plaid/plaid-python/blob/master/plaid/requester.py#L76) which means its never called without that arg. 

Thx for bringing the public nature of this to attention though, ive submitted this PR: https://github.com/plaid/plaid-python/pull/227

Closing this for now!
