### ISSUE TITLE
No error class defined for AUTH_ERROR type

### ISSUE THREAD

**Issue by eric-cc-su** [plaid/plaid-python#222]
[Plaid docs](https://plaid.com/docs/#auth-errors) describe an `AUTH_ERROR` error_type covering error codes:
- `PRODUCT_NOT_READY`
- `VERIFICATION_EXPIRED`

Following the existing pattern of using PlaidError child classes to map errors with known `error_type` values, it would make sense that an `AuthError` child class should exist as well.

If there is a reason why such a class should not exist I would be interested to know why.

It may be useful to note that there seems to be a discrepancy where the docs do not list `AUTH_ERROR` in the [Error Overview section](https://plaid.com/docs/#errors-overview) under the `error_type` field. Whether that is related to this issue is unclear.

**Comment by otherchen** [comment]
Hey @eric-cc-su, sorry for the delayed response. You are right! We are missing this class in this Python lib. I've made this PR to add the missing error classes https://github.com/plaid/plaid-python/pull/224.

**Comment by skylarmb** [comment]
looks like #224 was merged
