### ISSUE TITLE
Creating a public token with force_error override fails

### ISSUE THREAD

**Issue by karuhanga** [plaid/plaid-python#225]
[https://plaid.com/docs/#custom-sandbox](https://plaid.com/docs/#custom-sandbox)

Tried this;
```
client.Sandbox.public_token.create("ins_3", ["transactions"], dict(override_username='user_custom', override_password= dict(force_error="ITEM_LOGIN_REQUIRED")))
```

It fails with;
```
plaid.errors.InvalidRequestError: the following fields are not recognized by this endpoint: options.force_error
```

**Comment by Karuhanga** [comment]
My bad. Thanks!

If anyone lands on this in the future, I misunderstood the docs and this is what you should be trying to use instead.

https://plaid.com/docs/#testing-errors
