### ISSUE TITLE
Balances Product

### ISSUE THREAD

**Issue by jmcta** [plaid/plaid-python#293]
Just starting out with the python Plaid API, but I noticed that there was no `client.Balances.get()` call in the API.

Checking around I found that the class is in `api/accounts.py`, but it isn't included in `api/__init__.py` nor in `client.py`  

After changing `api/__init__.py` to `from plaid.api.accounts import Accounts, Balance` and adding `Balance` to the include portion of `client.py`, I can verify that it does call and work.  

Was this omission intentional?  Is the `Balance` endpoint available another way?

**Comment by skylarmb** [comment]
Hi there @jmcta i think you are looking for `client.Accounts.balance.get`. This mirrors how our api is structured: https://plaid.com/docs/api/products/#accountsbalanceget
