### ISSUE TITLE
Version is very different between github and pip

### ISSUE THREAD

**Issue by jmitchell33** [plaid/plaid-python#294]
The version of plaid-python on pip is 7.2.0, the version on Plaid's github is 2.3.3, and the version I currently have installed is 3.7.0.  What's going on here?

**Comment by skylarmb** [comment]
i believe we have not been pushing tags to github properly. 7.2.0 is the correct latest version. This should be fixed when we release 8.0 which uses a new automated publishing process.

**Comment by michaelhays** [comment]
Hey @skylarmb, is this still going to be fixed? The only v8 release in the [releases](https://github.com/plaid/plaid-python/releases) is 8.0.0b10.

**Comment by otherchen** [comment]
Hey @michaelhays! Thanks for surfacing - I believe we made a mistake pushing up the tag to github but the 8.0.0 version is actually now released on pypi! You can check it out here - https://pypi.org/project/plaid-python/.
