### ISSUE TITLE
Client version compatibility

### ISSUE THREAD

**Issue by casesolved-co-uk** [plaid/plaid-python#299]
Hi, just trying to figure out which client version works with which API version which isn't at all obvious unless you find the changelog.

Now I know the answer is `use the latest` but please could you put two things on your todo list:

- tag the different versions on github with a brief release note saying which APIs are supported. I can see the tags for beta releases 8... but the latest other tag is v2.3.3 and the latest on pypi is v7.2.0 !
- create a reference to the changelog and maybe a shortlist in the docs/github readme so that people know:
  - &gt; v7.0.0 supports API 2020-09-14
  - &gt; v3.2.0 supports API 2019-05-29, etc

Thanks!

**Comment by cgfarmer4** [comment]
hi @casesolved-co-uk --
You're right. This was an oversight I think on this repo. Something [like this ](https://github.com/plaid/plaid-ruby#versioning) what you're looking for?

**Comment by cgfarmer4** [comment]
We'll tag moving forward but the new table in the pr above for the `readme` should get you where you're going. please reopen if not.
