### ISSUE TITLE
Request returning connection error

### ISSUE THREAD

**Issue by tjquinn1** [plaid/plaid-python#315]
I am trying to retrieve transactions and as of recently been getting:

Error: HTTPSConnectionPool(host='d086e1b2cfdcade19e9ca0d8becad6.plaid.com', port=443): Max retries exceeded with url: /transactions/get (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1acbef2ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

I am able to create tokens without problem but for some reason getting transactions is not working. I am not making an obscene amount of requests or anything like that. This end point used work and only recently have I been having issues. Any ideas?

**Comment by kravien** [comment]
@tjquinn1 Did you find the solution for that issue?
