### ISSUE TITLE
missing standing_orders product in product model for plaid-python==8.0.0b9

### ISSUE THREAD

**Issue by adikshirsagar** [plaid/plaid-python#325]
for GB institutions, standing_orders is part of product values but not available in product model. This causes api fail

**getting this exception**: plaid.exceptions.ApiValueError: Invalid value for `value` (standing_orders), must be one of ['assets', 'auth', 'balance', 'identity', 'investments', 'liabilities', 'payment_initiation', 'transactions', 'credit_details', 'income', 'deposit_switch']

Note: getting this error in sandbox env

**Comment by saukap** [comment]
The YAML file (https://github.com/plaid/plaid-openapi/commit/e27384d76ab8aff0a61f52a8c6d50bd67ddac77a?branch=e27384d76ab8aff0a61f52a8c6d50bd67ddac77a&diff=unified#diff-007e82897f69503f2e98b0045e79d37b96a8a638c5eba2ed514dc8a6fcecd529R7872) has been updated so please re-generate the Python APIs.

**Comment by stephenjayakar** [comment]
@adikshirsagar @saukap just pushed b12 to pypi. Does updating fix your issues?

**Comment by phoenixy1** [comment]
going to close this for now, please re-open if the issue still occurs cc: @adikshirsagar @saukap
