### ISSUE TITLE
Oauth Support?

### ISSUE THREAD

**Issue by gusreyes01** [plaid/plaid-python#334]
I'm looking to implement Oath on our plaid integration using the plaid-python package, however, I don't see any reference to the Oauth implementation. Are there plans to implement this feature on a future release?

**Comment by phoenixy1** [comment]
@gusreyes01 all that is necessary in the library to implement oauth is the `redirect_uri` parameter (if not using Android) or the `android_package_name` parameter (if using Android) in the call to `/link/token/create`. These should be present, please let us know if they are not or if you have any other questions.

**Comment by gusreyes01** [comment]
Thanks @phoenixy1 , I resolved it.
