### ISSUE TITLE
ApiTypeError: Invalid type for variable 'category_id'. while getting trasactions

### ISSUE THREAD

**Issue by adikshirsagar** [plaid/plaid-python#339]
issue: ApiTypeError: Invalid type for variable 'category_id'.  Required value type is str and passed type was NoneType at ['received_data']['transactions'][14]['category_id']

when: while fetching transaction 
method : client.transactions_get(request)
version : plaid_python==8.0.0b12

**Comment by adikshirsagar** [comment]
and when I pass  _check_return_type=False as kwarg to transactions_get after this when I tried to convert it to dict with .to_dict method I get following error:

AttributeError: 'dict' object has no attribute '_composed_schemas'

**Comment by phoenixy1** [comment]
fyi @stephenjayakar

**Comment by phoenixy1** [comment]
I think this is happening because the category_id field is erroneously missing the nullable attribute. Fixing.

**Comment by phoenixy1** [comment]
sorry, erroneously closed this -- I think this will be fixed in the next release, but we haven't released it yet.

**Comment by phoenixy1** [comment]
I believe this should be fixed in 8.0.0b(13) released today, please re-open if it is not.

**Comment by priyankagagneja** [comment]
I am getting the exact error but for access_token variable. FWIW, i think the access token is not getting retrieved (I am trying to get the quickstart tutorial to work in sandbox). Please help.
