### ISSUE TITLE
Getting an error when using beta client to retrieve accounts

### ISSUE THREAD

**Issue by lemuelbarango** [plaid/plaid-python#342]
code snippet
```python
        response = client.accounts_get(AccountsGetRequest(access_token))
```

error
ApiTypeError plaid.model_utils in attempt_convert_item
Invalid type for variable 'current'. Required value type is float and passed type was NoneType at ['received_data']['accounts'][2]['balances']['current']

**Comment by phoenixy1** [comment]
thank you for the report! closing as same issue as #343
