### ISSUE TITLE
8.0.0b error request_id is not being returned by item get in API 2020-09-14

### ISSUE THREAD

**Issue by imtibbet** [plaid/plaid-python#349]
This field ([documentation](https://plaid.com/docs/api/items/#item-get-response-request-id_item)) went from nullable in API 2019-05-29 to non-nullable in API 2020-09-14, but it is not being included in the item get response in API 2020-09-14. This causes the beta client to blow up with error `__init__() missing 1 required positional argument: 'request_id'` when deserializing the ItemGetResponse (specifically the Error attribute deserialization).

`request_id` needs to either be marked as nullable again or it needs to be provided, otherwise fetching items will continue to blow up when they are in an error state. I have not conceived of a workaround yet and would welcome either a quick fix or a suggested workaround.

**Comment by phoenixy1** [comment]
fixed this internally, will be resolved with the next beta version

**Comment by imtibbet** [comment]
The resolution to this issue appears to be missing from the PR https://github.com/plaid/plaid-python/pull/351

**Comment by phoenixy1** [comment]
I believe this should be fixed in 8.0.0b(13) released today; does it resolve the issue for you?

**Comment by imtibbet** [comment]
The initial results look good, but I'll know for sure after our overnight jobs run tonight.

**Comment by phoenixy1** [comment]
@imtibbet any updates?

**Comment by imtibbet** [comment]
Resolved!
