### ISSUE TITLE
8.0.0b(12) `ApiTypeError` on `identity_get` request

### ISSUE THREAD

**Issue by movsho** [plaid/plaid-python#352]
Hey guys,
A request to identity's get throws an ApiTypeError because of mandatory field `country`.
It's expected to be mandatory, but for my request it arrived as None.

`(ApiValueError("Invalid inputs given to generate an instance of 'AccountIdentityAllOf'. The input data was invalid for the allOf schema 'AccountIdentityAllOf' in the composed schema 'AccountIdentity'. Error=Invalid type for variable 'country'. Required value type is str and passed type was NoneType at ['received_data']['accounts'][0]['owners'][0]['addresses'][0]['data']['country']"),)`

`transactions_get`, for the same access-token, works as expected.

double verified it by editing the plaid-python lib's `address_data` and changing `country` to be `'country': (str, none_type)` and got no error there.

**Comment by phoenixy1** [comment]
thanks for the report -- I am just checking with the team to make sure this is a bug in the API specification and not in the data that's being returned by the endpoint. Either way, we'll make sure it gets fixed.

**Comment by phoenixy1** [comment]
I believe this should be fixed in 8.0.0b(13) released today, please re-open if it is not.
