### ISSUE TITLE
Support for pending transactions?

### ISSUE THREAD

**Issue by nicksergeant** [plaid/plaid-python#36]
It seems support for pending transactions must pass through to the `/connect` endpoint as per the docs:

![http://i.nick.sg/image/321k2Q0g353N/Image%202015-11-30%20at%202.05.46%20PM.png](http://i.nick.sg/image/321k2Q0g353N/Image%202015-11-30%20at%202.05.46%20PM.png)

However, passing this option like this does not appear to return pending transactions:

```
response = client.connect('usaa', {
    'username': 'user',
    'password': 'pass',
    'pin': '1234'
}, options={
    'pending': True
})
```

This Python lib seems to want the `pending` arg on `connect_get` here: https://github.com/plaid/plaid-python/blob/master/plaid/client.py#L390, but that doesn't appear to work, either.

Not sure if this issue is with `plaid-python`'s implementation or an issue with the API.

**Comment by andresn** [comment]
Hi there, any chance we can get some help with this? We haven't been able to see pending transactions to date.

@mikaelm1

**Comment by michaelckelly** [comment]
@andresn  - Sorry to hear that this is still an issue. Can you confirm that you're seeing this w/ the latest version of the library?

**Comment by Lezeper** [comment]
I think it is a issue with the API endpoint. I also didn't get any pending transactions...
