### ISSUE TITLE
Typo Fix Request: "SBV_API" to "SVB_API"

### ISSUE THREAD

**Issue by linyahu** [plaid/plaid-python#363]
Hi! I'm using the `plaid-python` library to integrate with Plaid and SVB. There's a typo in the `processor_token_create_request.py` file line 70:  `'SBV_API': "sbv_api"` should be `'SVB_API': "svb_api"`. Having `sbv_api` as the processor throws an error when hitting the Plaid endpoint:

```
*** plaid.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Wed, 25 Aug 2021 20:25:33 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '219', 'Connection': 'keep-alive', 'Plaid-Version': '2020-09-14'})
HTTP response body: {
  "display_message": null,
  "error_code": "INVALID_PROCESSOR",
  "error_message": "The provided processor is invalid.",
  "error_type": "INVALID_INPUT",
  "request_id": "U7NoiLpRdUpeBYi",
  "suggested_action": null
}
```

I'm able to bypass the error locally by just changing the value in that file, but I think we will run into issues when trying to deploy this to production. Could you help change that typo?

Thank you!

**Comment by phoenixy1** [comment]
thank you for the report, this will be fixed in the next release (expected within 1-2 weeks)

**Comment by phoenixy1** [comment]
should now be fixed with today's release
