### ISSUE TITLE
Unable to fetch link_token

### ISSUE THREAD

**Issue by Khachdallak02** [plaid/plaid-python#384]
Trying to follow quickstart guide to setup back and front end fro Plaid. 
I am getting the following error:
 Unable to fetch link_token: please make sure your backend server is running and that your .env file has been configured correctly.
I ensured that backend server is running. 
Below is the .env file:
PLAID_CLIENT_ID=REDACTED
PLAID_SECRET=REDACTED
PLAID_ENV=sandbox
PLAID_PRODUCTS=auth,transactions
PLAID_COUNTRY_CODES=US,CA
PLAID_REDIRECT_URI=http://localhost:3000/

Other people on internet were facing the same issue, none of them were answered. Any help appreciated.

**Comment by phoenixy1** [comment]
Can you take a look at the request and response for the actual call being made to /link/token/create and provide them here (with the client id and secret redacted)? I believe this info should be in the logs output by the console.

**Comment by Khachdallak02** [comment]
After restarting the computer, everything works now. Thanks
