### ISSUE TITLE
Transactions Response Date

### ISSUE THREAD

**Issue by linus-pi** [plaid/plaid-python#388]
The API Object "date": is coming out as datetime.date(yyyy,mm,dd).  Should it not display the date as in the response example on the plaid API example?  According to the example and prior versions the output for today's date would be 2021-12-07.  Instead the output is datetime.date(2021,12,7).

**Comment by phoenixy1** [comment]
This is how the Python OpenAPI generator by default interprets date-time strings in the OpenAPI file -- we will update the example to match.

**Comment by linus-pi** [comment]
Date out of the 2019-05-29 API is consistent and as shown in the example.  Should it not be consistent?

**Comment by phoenixy1** [comment]
@linus-pi the client libraries for the 2019-05-29 API and 2020-09-14 API have substantial interface differences as the latter is generated automatically by OpenAPI generator. OpenAPI generator will interpret date-time strings as datetime objects if the language has an equivalent object. We'll make sure to add this note to the README to make migration between the two versions easier.
