### ISSUE TITLE
Retrieving api url and status code of responses

### ISSUE THREAD

**Issue by nickatnight** [plaid/plaid-python#428]
Hello,

What is the preferred method to get the request url and response status code (for 2xx codes) from a ModelNormal response object?

**Comment by phoenixy1** [comment]
@vorpus do you happen to know the answer to this one (or know who might)? I'm not a deep expert in the python libraries.

**Comment by phoenixy1** [comment]
@otherchen do you happen to know the answer to this one (or know who might)? I'm not a deep expert in the python libraries.

**Comment by spacether** [comment]
If the client is regenerated with openapi-generator v6.2.0 then the response will be included when one gets a result back from an endpoint. [One can see that response here](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/paths/pet/post.py#L101)
api_response.response is type [urllib3.HTTPResponse which includes](https://urllib3.readthedocs.io/en/stable/reference/urllib3.response.html#response)
- status
- request_url
