### ISSUE TITLE
Can't use plaid properly in python, getting no attribute errors

### ISSUE THREAD

**Issue by ArifNawaz36** [plaid/plaid-python#430]
I have installed the plaid library for python by following the instructions mentioned in this repo. But after installation I am facing this error, **AttributeError: module 'plaid' has no attribute 'Configuration'**. I have tried to get other values from the library but facing the same, like plaid.ApiClient results in **module 'plaid' have no attribute 'ApiClient'**. I am getting all the IntelliSense from the library and importing things as well but still facing these issues.

plaid-python - v9.9.0

python - v3.8/v3.10

`pip install plaid-python`

`import plaid`
`configuration = plaid.Configuration(
    host=plaid.Environment.Sandbox,
    api_key={
        'clientId': client_id,
        'secret': secret,
    }
)`

I have searched a lot but couldn't find any solution. Need guidance here
Thanks

**Comment by phoenixy1** [comment]
Can you try running through the Quickstart instructions and seeing if they work for you? https://plaid.com/docs/quickstart/ this can help isolate the cause to see whether the issue is something related to your specific project configuration or code.

**Comment by ArifNawaz36** [comment]
The issue has been resolved by changing versions of `plaid-python`. I have changed my version from v9.9.0 to v9.1.0. I think the latest version may contain some breaking changes.

Closing this issue, thank you for your prompt reply.
