### ISSUE TITLE
Is there a chance that the plaid dev team is working on or in future will work on integration of Plaid API using R Programming language

### ISSUE THREAD

**Issue by priyankagagneja** [plaid/plaid-python#460]
I see Python endpoints but nothing is available for a R user to work with this product.

**Comment by phoenixy1** [comment]
Hi, we don't currently have any plans to create an R client library. You have a few options for working with Plaid:
1) Use an HTTP request library such as httr to send HTTP POST requests directly to the Plaid API. This is probably the easiest option.
2) Generate your own R client library using our publicly available API specification at https://github.com/plaid/plaid-openapi along with the openapi generator https://github.com/OpenAPITools/openapi-generator 
3) Create a component for making Plaid requests that does not use R.
