### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by rahularyaflyfin** [plaid/plaid-python#468]
after upgrading from legacy to 12.0.0 version facing http.client.RemoteDisconnected error many times.

**Comment by phoenixy1** [comment]
@rahularyaflyfin are you still experiencing this error? If so, can you provide more details about the situation that's triggering it and what you've done so far to troubleshoot?

**Comment by phoenixy1** [comment]
closing due to no response, feel free to re open if needed
