### ISSUE TITLE
Download income documents

### ISSUE THREAD

**Issue by MariaMozgunova** [plaid/plaid-python#472]
Hello,

Thank you for your great work and the library you are building.

I have a question related to the best practices to download income documents. An [income document URL](https://plaid.com/docs/api/products/income/#credit-payroll_income-get-response-items-payroll-income-form1099s-document-metadata-download-url) is returned from the endpoint `/credit/payroll_income/get` in the field `download_url`.

What would be the best approach to download a document at `download_url`?

Plaid support told me I can do with a simple GET request. Should it be `requests.get` or there is some method in the Python Plaid client library?

I am asking because if the plain GET request would work then I as well could see a document by opening a link in the browser. However, I see an error instead:

```
{
  "display_message": null,
  "error_code": "INCOME_VERIFICATION_DOCUMENT_NOT_FOUND",
  "error_message": "the requested data was not found. Please check the ID supplied.",
  "error_type": "INCOME_VERIFICATION_ERROR",
  "request_id": "aCytDdGqf0Rahnr",
  "suggested_action": null
}
```

Best regards,
Maria

**Comment by phoenixy1** [comment]
@MariaMozgunova can you submit a support ticket (or write back on your existing support ticket) for this issue? As far as I know the GET request does not need to be made in any special way, so there is probably something else causing the request to fail; support would be best positioned to troubleshoot and investigate why this API call didn't succeed.

**Comment by MariaMozgunova** [comment]
I contacted Plaid Support.
It turned out that the download URL expires after a few minutes after calling `/credit/payroll_income/get`.
Thank you for your response!
