### ISSUE TITLE
Replace HTTPResponse.getheader() with HTTPResponse.headers.get(name, default)

### ISSUE THREAD

**Issue by calderwoodra** [plaid/plaid-python#474]
I see the following deprecation warning when attempting to generate a link token:

```
/usr/local/lib/python3.9/site-packages/plaid/rest.py:42: DeprecationWarning: HTTPResponse.getheader() 
is deprecated and will be removed in urllib3 v2.1.0. Instead use HTTPResponse.headers.get(name, default). 
return self.urllib3_response.getheader(name, default)
```

**Comment by phoenixy1** [comment]
This is a warning that can be safely ignored. (The code in question that's being warned about is created by a code generator, and we can't address this issue directly without updating to a version of the code generator that is a major rewrite.)

**Comment by phoenixy1** [comment]
Just wanted to update that a fix has been pushed, so this is anticipated to be fixed in the next release of the plaid-python client library.
