### ISSUE TITLE
ApiAttributeError: KYCCheckPhoneSummary has no attribute 'area_code'

### ISSUE THREAD

**Issue by scpaes** [plaid/plaid-python#480]
Good morning, everyone. I'm facing an issue while trying to Retrieve a previously created identity verification. This exception is being thrown.

venv/lib64/python3.10/site-packages/plaid/api_client.py:769: in __call__
    return self.callable(self, *args, **kwargs)
venv/lib64/python3.10/site-packages/plaid/api/plaid_api.py:7194: in __identity_verification_get
    return self.call_with_http_info(**kwargs)
venv/lib64/python3.10/site-packages/plaid/api_client.py:831: in call_with_http_info
    return self.api_client.call_api(
venv/lib64/python3.10/site-packages/plaid/api_client.py:406: in call_api
    return self.__call_api(resource_path, method,
venv/lib64/python3.10/site-packages/plaid/api_client.py:221: in __call_api
    return_data = self.deserialize(
venv/lib64/python3.10/site-packages/plaid/api_client.py:322: in deserialize
    deserialized_data = validate_and_convert_types(
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1354: in validate_and_convert_types
    converted_instance = attempt_convert_item(
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1241: in attempt_convert_item
    return deserialize_model(input_value, valid_class,
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1161: in deserialize_model
    return model_class(**kw_args)
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1526: in wrapped_init
    return fn(self, *args, **kwargs)
venv/lib64/python3.10/site-packages/plaid/model/identity_verification_get_response.py:236: in __init__
    self.kyc_check = kyc_check
venv/lib64/python3.10/site-packages/plaid/model_utils.py:165: in __setattr__
    self[attr] = value
venv/lib64/python3.10/site-packages/plaid/model_utils.py:350: in __setitem__
    self.set_attribute(name, value)
venv/lib64/python3.10/site-packages/plaid/model_utils.py:137: in set_attribute
    value = validate_and_convert_types(
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1354: in validate_and_convert_types
    converted_instance = attempt_convert_item(
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1241: in attempt_convert_item
    return deserialize_model(input_value, valid_class,
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1161: in deserialize_model
    return model_class(**kw_args)
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1526: in wrapped_init
    return fn(self, *args, **kwargs)
venv/lib64/python3.10/site-packages/plaid/model/kyc_check_details.py:192: in __init__
    self.phone_number = phone_number
venv/lib64/python3.10/site-packages/plaid/model_utils.py:165: in __setattr__
    self[attr] = value
venv/lib64/python3.10/site-packages/plaid/model_utils.py:350: in __setitem__
    self.set_attribute(name, value)
venv/lib64/python3.10/site-packages/plaid/model_utils.py:137: in set_attribute
    value = validate_and_convert_types(
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1354: in validate_and_convert_types
    converted_instance = attempt_convert_item(
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1241: in attempt_convert_item
    return deserialize_model(input_value, valid_class,
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1161: in deserialize_model
    return model_class(**kw_args)
venv/lib64/python3.10/site-packages/plaid/model_utils.py:1526: in wrapped_init
    return fn(self, *args, **kwargs)
venv/lib64/python3.10/site-packages/plaid/model/kyc_check_phone_summary.py:172: in __init__
    setattr(self, var_name, var_value)
venv/lib64/python3.10/site-packages/plaid/model_utils.py:165: in __setattr__
    self[attr] = value
venv/lib64/python3.10/site-packages/plaid/model_utils.py:350: in __setitem__
    self.set_attribute(name, value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = {'summary': 'no_match'}, name = 'area_code', value = 'no_data'

    def set_attribute(self, name, value):
        # this is only used to set properties on self
    
        path_to_item = []
        if self._path_to_item:
            path_to_item.extend(self._path_to_item)
        path_to_item.append(name)
    
        if name in self.openapi_types:
            required_types_mixed = self.openapi_types[name]
        elif self.additional_properties_type is None:
>           raise ApiAttributeError(
                "{0} has no attribute '{1}'".format(
                    type(self).__name__, name),
                path_to_item
E               plaid.exceptions.ApiAttributeError: KYCCheckPhoneSummary has no attribute 'area_code' at ['received_data']['kyc_check']['phone_number']['area_code']

venv/lib64/python3.10/site-packages/plaid/model_utils.py:114: ApiAttributeError

python: 3.10.12
plaid-python: 11.6.0

**Comment by phoenixy1** [comment]
@scpaes This is due to a bug that has been fixed in version 12.0.0 of the python client library. If you upgrade to the latest version, this should be resolved.
