### ISSUE TITLE
README contains erroneous code

### ISSUE THREAD

**Issue by tarkatronic** [plaid/plaid-python#49]
In the README, there is a section with the following code:

```python
from plaid import Client

client = Client.config({
    'url': 'https://tartan.plaid.com',
    'suppress_http_errors': True,
})
response = client.connect('bofa', {
    'username': '[something_invalid]',
    'password': '***'
})
```

However, this doesn't actually work properly, as `config()` doesn't return a Client instance. It would have to look more like:

```python
from plaid import Client

Client.config({
    'url': 'https://tartan.plaid.com',
    'suppress_http_errors': True,
})
client = Client('test_id', 'test_secret')
response = client.connect('bofa', {
    'username': '[something_invalid]',
    'password': '***'
})
```

Alternatively, correct me if I'm wrong, but couldn't I just use:

```python
from plaid import Client

client = Client('test_id', 'test_secret')
client.base_url = 'https://tartan.plaid.com'
client.suppress_http_errors = True
response = client.connect('bofa', {
    'username': '[something_invalid]',
    'password': '***'
})
```

**Comment by Bpless** [comment]
@tarkatronic, thanks for this report.  

The sample code in the README is incorrect.  We'll fix that. 

To your broader point, I think that the following code should live in a constructor

```python
client.base_url = 'https://tartan.plaid.com'
client.suppress_http_errors = True
```
Client.config was an attempt to configure on a class level, with the assumption that you would not want to vary things like url and suppress_http_errors on a per instance basis.

It is confusing, though, so perhaps those options should be passed to the constructor.
