### ISSUE TITLE
Hosted link is not in the create link token response

### ISSUE THREAD

**Issue by Nikhilkoneru** [plaid/plaid-python#524]
Hosted link url is not in the response

<img width="1170" alt="Screenshot 2024-09-03 at 4 58 49 PM" src="https://github.com/user-attachments/assets/8bf99264-814f-4efc-8122-14dbced75671">

Response

```{'expiration': datetime.datetime(2024, 9, 4, 0, 48, 32, tzinfo=tzlocal()),
 'link_token': 'link-sandbox-83b32728-d48f-454f-a84f-adea936863ad',
 'request_id': '3Wn4sBt2wIVlWg6'}```

**Comment by phoenixy1** [comment]
This is as-expected if you have not yet had hosted link enabled for your account. You can file a support ticket or contact your account manager to enable hosted link.

<img width="711" alt="image" src="https://github.com/user-attachments/assets/664843b8-fd2c-40a2-a9fb-f5247e770cab">
