### ISSUE TITLE
[Bug] Improper handling of liability get request response format for None account_number fields

### ISSUE THREAD

**Issue by jaredwelch1** [plaid/plaid-python#538]
```
ApiTypeError: Invalid type for variable 'account_number'. Required value type is str and passed type was NoneType at ['received_data']['liabilities']['mortgage'][0]['account_number']

```

I am using the plaid example for liability request in python: 

https://plaid.com/docs/api/products/liabilities/#liabilitiesget

```
# retrieve Liabilities data for an item
request = LiabilitiesGetRequest(access_token=access_token)
response = client.liabilities_get(request)
liabilities = response['liabilities']
```

expected behavior would be that this response is returned with a None for the field or the response is updated on the plaid api side to always ensure the field is not None

I validated that the request works fine using curl with the same params 

Let me know if I can provide more context.

**Comment by phoenixy1** [comment]
Thank you for the report! A fix has been merged and will be released with the next python client library release (most likely in January).
