### ISSUE TITLE
README Examples Don't Work

### ISSUE THREAD

**Issue by phoxelua** [plaid/plaid-python#55]
Two README examples fail. One:
```python
from plaid import Client
from plaid import errors as plaid_errors
from plaid.utils import json


client = Client()
institutions = json.loads(client.institutions().content)
categories = json.loads(client.categories().content)
```
And it breaks cause the Client doesn't actually allow no params for `client_id` and `secret`. Even if I use a Client with a legitimate params, as below it will fail because of `json.loads` (see below).

I also tried this example (with my actual client, username, password, etc):

```python
from plaid import Client
from plaid import errors as plaid_errors
from plaid.utils import json


client = Client(client_id='***', secret='***')
account_type = 'bofa'

try:
    response = client.connect(account_type, {
     'username': '***',
     'password': '***'
    })
except plaid_errors.PlaidError:
     pass
else:
    connect_data = json.loads(response.content)
``` 

This works with a 200 but `response.content` is a byte object and not a string. So json.loads fails. This happens using both python's json library and plaid's json util. `response.text` and `response.json()` still give me what I want so there's a workaround.

I'm using python 3.4 and it looks like you guys added support for that in the 1.10.

**Comment by lucamartinetti** [comment]
Thanks for reporting this. I can reproduce both the issue. Will fix shortly

**Comment by lucamartinetti** [comment]
Fixed in latest version. Thanks for reporting
