### ISSUE TITLE
Income and Risk Support

### ISSUE THREAD

**Issue by bsgilber** [plaid/plaid-python#56]
I am able to use the Plaid Link to authenticate and pull user data, but I am having trouble getting all the information that the API reference says is available.

Currently I can use:
- info_get() to find personal information
- auth_get() to find balances, account information
- connect_get() for transaction information

Am I just not seeing the documentation for risk and income or is that a WiP?

Thanks!

**Comment by lucamartinetti** [comment]
Just added Risk and Income support in 1.4.0. Let me know your feedback!
