### ISSUE TITLE
Adding other banks to API

### ISSUE THREAD

**Issue by seersuckerguy** [plaid/plaid-python#61]
Is the below list exhaustive for banks to which I am able to connect? (Link to Plaid's list: (https://plaid.com/docs/api/#institution-overview)

American Express
Bank of America
Capital One 360
Charles Schwab
Chase
Citi
Fidelity
Navy Federal Credit Union
PNC
SunTrust
TD Bank
US Bank
USAA
Wells Fargo

**Comment by angelagao28** [comment]
There are also longtail institutions, which can be found here: https://plaid.com/docs/api/#long-tail-institutions

**Comment by seersuckerguy** [comment]
Bingo! Thanks much, @angelagao28
