### ISSUE TITLE
What about restricting the date when pulling transactions?

### ISSUE THREAD

**Issue by ronenmagid** [plaid/plaid-python#65]
Do you have support for limiting the number of pulled transactions by what's available for the options parameter? e.g. {"gte": "2016-08-17"}.

**Comment by roucha** [comment]
@ronenmagid I just tried including the options parameter to limit the number of pulled transactions and it worked fine. See code below

```
import requests
url = 'https://tartan.plaid.com/connect/get'
payload = {'client_id': '***',
           'secret': '***',
           'access_token': '***',
           'options': 
               {'gte':'2016-08-28'}
           }

r = requests.post(url, json = payload)
print(r.text)
```
