### ISSUE TITLE
Institution Listing

### ISSUE THREAD

**Issue by battery514** [plaid/plaid-python#74]
I pulled this code from the documentation:

    # Pull 50 institutions that support both Auth and Connect
    institutions = client.institutions(count=50, offset=0, products=["auth","connect"]).json()

But that results in the below error:

    TypeError: institutions() got an unexpected keyword argument 'count'

**Comment by michaelckelly** [comment]
@battery514  - Are you using the latest version of the module (`1.5.0`)? It was published this morning

**Comment by battery514** [comment]
@michaelckelly - I was not, but I just upgraded plaid-python to 1.5.0, reran the program, and received the same error.  Below is my full code, in the event it's helpful.

    from plaid import Client

    client = Client(client_id='redacted', secret='redacted')

    # Pull 50 institutions that support both Auth and Connect
    institutions = client.institutions(count=50, offset=0, products=["auth","connect"]).json()

**Comment by michaelckelly** [comment]
@battery514 - Yikes, that's an error in the README! That should read:

```
# Pull 50 institutions that support both Auth and Connect
institutions = client.institutions_all(count=50, offset=0, products=["auth","connect"]).json()
```

**Comment by michaelckelly** [comment]
This test case may also be helpful - https://github.com/plaid/plaid-python/blob/master/tests/integration/test_client.py#L254-L257

Fixing README now

**Comment by battery514** [comment]
Perfect - thanks!
