### ISSUE TITLE
Readme misleading for App Engine requests

### ISSUE THREAD

**Issue by onejgordon** [plaid/plaid-python#76]
On GAE plaid-python uses urlfetch, which returns a _URLFetchResult object. This object has no json() method.

Readme should read (for the GAE case): 

```
client = Client(client_id='***', secret='***', access_token='usertoken')
response = client.connect_get()
if response.status_code == 200:
    transactions = json.loads(response.content)
```

**Comment by michaelckelly** [comment]
Thanks for raising this @onejgordon, I ported this issue to https://github.com/plaid/plaid-python-legacy/issues/2.

Please re-open if this issue is still relevant with version 2.0.x.
