### ISSUE TITLE
`requests` requirement too strict

### ISSUE THREAD

**Issue by glyph** [plaid/plaid-python#78]
https://github.com/plaid/plaid-python/blob/master/setup.py#L20 uses an `==` constraint to pin `requests` to an exact version.  This prevents automatic security updates of `requests` on projects which depend on `plaid-python`, which seems like a problem.

In general, `setup.py` should be lenient and `requirements.txt` should be strict, as documented in Donald Stufft's [canonical article on the subject](https://caremad.io/posts/2013/07/setup-vs-requirement/).

Is there a specific reason that this requirement is pinned?

**Comment by joyzheng** [comment]
No, thanks for pointing this out! We just merged #77, which should fix this; it will go out with the next release.

**Comment by glyph** [comment]
Thanks, @joyzheng!  Looking forward to the next release.

**Comment by joyzheng** [comment]
Thanks for your patience! 2.0.1 has been released now.

**Comment by glyph** [comment]
Thanks again.
