### ISSUE TITLE
Update README sample

### ISSUE THREAD

**Issue by pamolloy** [plaid/plaid-python#8]
I believe line 22 in the README.md should be `client.connect_step` instead of `client.step`.

Also the MFA isn't entirely clear to me. My BoA account was locked while trying to connect to it. I believe the following should support multiple security questions, but the answers kept being rejected. 
``` python
if connect.ok:
    response = json.loads(connect.content)
    while response['mfa']:
        answer = raw_input(response['mfa'][0]["question"] + ": ")
        step = client.connect_step(account_type='bofa', mfa=answer)
        reponse = step.content
    if step.ok:
        transactions = json.loads(step.content)
```

Also, is there a difference between `Client.auth_step()` and `Client.connect_step()`?

And finally `transactions = json.loads(step.content)` doesn't make sense to me. Wouldn't one need to call `Client.transactions()` to get a list of transactions?

**Comment by michaelckelly** [comment]
@pamolloy:

I realize this issue is a few months old now, but we've just released a major refactor of this library as version `1.0.x`. The release features a significantly expanded [examples](https://github.com/plaid/plaid-python#getting-started) section (including MFA support examples).
