### ISSUE TITLE
Can't install using pip install

### ISSUE THREAD

**Issue by ioliverm** [plaid/plaid-python#86]
pip install plaid-python throws an exception saying:

ImportError: No module named 'requests'

**Comment by joyzheng** [comment]
@ioliverm thanks for catching this! I'm working on a fix; in the meantime, you can work around it by installing requests before installing `plaid-python`: `pip install requests`.

**Comment by ioliverm** [comment]
Hi!

We tried that, the issue for us is that we install plaid-python in an automated script involving a builder docker container and using pip wheel. We tried, in that scenario, to install requests before installing plaid-python, but nothing we tried worked. In the meantime, until there's a fix, we fixed the plaid-python requirement version to 1.5.0, that works for us.

We'll look forward to hearing from you guys when the fix for 2.0.0 is ready.

Cheers!

Ivan

**Comment by michaelckelly** [comment]
@ioliverm - Version  2.0.1 was just published and should be live on pypi shortly!
