### ISSUE TITLE
most _options params are not documented in the api package

### ISSUE THREAD

**Issue by zevaverbach** [plaid/plaid-python#95]
I'm happy to add those if you can provide API documentation for them:  For example, while there's an `_options` parameter for `Accounts.get`, there are no parameters documented for `accounts/get` [here](https://plaid.com/docs/api/#accounts).

**Comment by joyzheng** [comment]
Thanks for volunteering!

Here's the note in `docs_source/index.rst` about the `_options` objects:

```
Many API endpoints accept optional parameters via an `_options` object in the raw JSON. 
To improve forward compatibility as options are added, the Python functions for these 
endpoints also include an `_options` argument. However, it is recommended that you 
pass in options using the provided keyword arguments where possible.
```

To recap, the `_options` objects exist primarily for flexibility in and future-proofing the library; the options in them should already be documented under their respective keyword arguments, however. 

Good catch with the `accounts/get`; we seem to have gotten a bit overzealous about adding the `_options` parameters to functions in the library even when it wasn't in the API :). 

I'm going to close this issue for now; please feel free to open a PR if you have ideas for making the documentation on `_options` clearer or more visible.
