### ISSUE TITLE
ConnectionError when running Python Quickstart code 

### ISSUE THREAD

**Issue by syzhang88** [plaid/plaid-python#97]
Hello,

I get this error when trying to run the python quickstart code on this github. I also tried running the node version, which returned a 400 INVALID_REQUEST error, with error code INVALID_FIELD.

Specifically, here is the screenshot when I try to log in using user_good on sandbox mode:

<img width="572" alt="screen shot 2017-06-22 at 10 12 00 am" src="https://user-images.githubusercontent.com/8379968/27457855-1b59b4f4-575b-11e7-899b-1eae5a495636.png">

Does anyone know what could be the issue? Aside from adding my api keys, I have not modified the code. I have used pip to install all the relevant packages.

Thanks!
Sam

**Comment by r-ohan** [comment]
Hi @syzhang88, are you still having this issue?

Can you please try again after running the following: ```pip install requests[security]```

Here's more context: https://stackoverflow.com/questions/31811949/pip-install-requestssecurity-vs-pip-install-requests-difference

**Comment by siddgood** [comment]
I had the same issue, but `pip install requests[security]` seems to resolve the issue.
